---
title: "R Markdown'da müxtəlif temalar"
author: 
  name: "Müəllif: Tərlan Cəbiyev"
  email: "email@gmail.com"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: default #default,bootstrap,cerulean,cosmo,darkly,flatly,journal,lumen,paper,readable,sandstone,simplex,spacelab,united,yeti
---

# R Markdown

## Highcharts

```{r verilən isim, include=FALSE}
library(tidyverse)
library(highcharter)

dataset <- dslabs::gapminder
```

### default

```{r}
dataset %>% 
  group_by(continent) %>% 
  summarise(life_expectancy = mean(life_expectancy)) %>% 
  hchart("line", hcaes(x = continent,y = life_expectancy)) 
```

### echo=FALSE

```{r echo=FALSE}
dataset %>% 
  group_by(continent) %>% 
  summarise(life_expectancy = mean(life_expectancy)) %>% 
  hchart("line", hcaes(x = continent,y = life_expectancy)) 
```

### echo=TRUE

```{r echo=TRUE}
dataset %>% 
  group_by(continent) %>% 
  summarise(life_expectancy = mean(life_expectancy)) %>% 
  hchart("line", hcaes(x = continent,y = life_expectancy)) 
```

### include=FALSE

```{r include=FALSE}
dataset %>% 
  group_by(continent) %>% 
  summarise(life_expectancy = mean(life_expectancy)) %>% 
  hchart("line", hcaes(x = continent,y = life_expectancy)) 
```

### warning=TRUE

```{r warning=TRUE}
dataset %>% 
  mutate(region = as.numeric(as.character(region))) %>% 
  group_by(continent) %>% 
  summarise(life_expectancy = mean(life_expectancy)) %>% 
  hchart("line", hcaes(x = continent,y = life_expectancy)) 
```

### warning=FALSE

```{r warning=FALSE}
dataset %>% 
  mutate(region = as.numeric(as.character(region))) %>% 
  group_by(continent) %>% 
  summarise(life_expectancy = mean(life_expectancy)) %>% 
  hchart("line", hcaes(x = continent,y = life_expectancy)) 
```

## GGplots

### fig.height=2, fig.width=4

```{r fig.height=2, fig.width=4}
dataset %>% 
  group_by(continent) %>% 
  summarise(life_expectancy = mean(life_expectancy)) %>% 
  ggplot(aes(x = continent,y = life_expectancy, fill = continent)) +
  geom_col(show.legend = F)
```

### fig.height=12, fig.width=20

```{r fig.height=12, fig.width=20}
dataset %>% 
  group_by(continent) %>% 
  summarise(life_expectancy = mean(life_expectancy)) %>% 
  ggplot(aes(x = continent,y = life_expectancy, fill = continent)) +
  geom_col(show.legend = F)
```
